# Generated by Django 5.2.4 on 2025-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "metric",
                    models.CharField(
                        blank=True, help_text="e.g., '94% email reach'", max_length=100
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField()),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
            ],
            options={
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="John", max_length=100)),
                (
                    "title",
                    models.CharField(
                        default="AI Developer & Automation Specialist", max_length=200
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Automating the Future: One Bot at a Time",
                        max_length=300,
                    ),
                ),
                ("bio", models.TextField(help_text="Brief intro about yourself")),
                (
                    "detailed_bio",
                    models.TextField(help_text="Detailed bio for About page"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "cv_file",
                    models.FileField(
                        blank=True, help_text="Downloadable CV", upload_to="documents/"
                    ),
                ),
                ("profile_image", models.ImageField(blank=True, upload_to="profile/")),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming Languages"),
                            ("frameworks", "Frameworks & Libraries"),
                            ("tools", "Tools & Platforms"),
                            ("databases", "Databases"),
                            ("ai_ml", "AI/ML Technologies"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveIntegerField(default=5, help_text="1-10 scale"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="testimonials/")),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
