# Generated by Django 5.2.4 on 2025-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(default="AI DNAs / John", max_length=100),
        ),
    ]
